### ISSUE TITLE
KotlinObjectMapperFactory is not forwards compatible

### ISSUE THREAD

**Issue by Sineaggi** [temporalio/sdk-java#2071]
## Expected Behavior
KotlinObjectMapperFactory works

## Actual Behavior
KotlinObjectMapperFactory crashes with MethodNotFoundError

## Steps to Reproduce the Problem

  1. Use temporal kotlin
  1. Upgrade jackson kotlin library
  1. Crash

## Specifications

  - Version:
  - Platform:

Instead of using a deprecated method, it would have been best to try using the builder first, then fall back to the deprecated KotlinModule constructor. Alternatively, we should just use the builder as we can't even pick which KotlinModule constructor we compile against.

**Comment by kevinrobayna** [comment]
I've opened #3095 to fix this.

**Root cause:** `KotlinObjectMapperFactory.new()` called `KotlinModule()` with no arguments. Kotlin compiles that into a call to a hidden variant of the deprecated constructor that fills in every default argument. That compiled call is tied to the constructor's exact parameter list in the Jackson version the SDK was built with (2.15.4). The parameter list changed in 2.11, 2.12 and 2.16, so the SDK only worked with jackson-module-kotlin 2.12 through 2.15. Every other version failed with:

```
java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.module.kotlin.KotlinModule.<init>(int, boolean, boolean, boolean, com.fasterxml.jackson.module.kotlin.SingletonSupport, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)'
```

The deprecated constructor was meant to keep old Jackson versions working, but it also failed on 2.9.0 through 2.11, which are at the bottom of the supported `[2.9.0,)` range.

**Fix:** The factory now calls `registerKotlinModule()` and lets jackson-module-kotlin build the module itself. That function's signature hasn't changed since 2.9.0. I built the SDK against 2.15.4 and ran it against 2.9.0, 2.10, 2.11, 2.12, 2.13, 2.14, 2.15.4, 2.16, 2.17, 2.18, 2.19 and 2.21.4. The old code only worked on 2.12–2.15; the new code works on all of them. The public API doesn't change.

Once this ships, you can drop the workaround and go back to `KotlinObjectMapperFactory.new()`.

@seregamorph: this fixes the 2.x line, including 2.16+ and the latest 2.21.x. Jackson 3.x moved to new package names (`tools.jackson.*`) and isn't supported by the SDK's core `JacksonJsonPayloadConverter` either, so 3.x support would be a separate change.
